### ISSUE TITLE
Youtube link broken. https://styfle.dev/blog/software-shepherd

### ISSUE THREAD

**Issue by kouhe3** [styfle/styfle.dev#537]
Software Shepherd implies a fast, autonomous livestock that might break if left unmaintained. Sheep without a shepherd can make [poor decisions](https://www.youtube.com/watch?v=W_4S5yBkSpU) so there is an active role for the shepherd.

this url is broken...

Did you back up this video?

**Comment by styfle** [comment]
Oh no. It was a sheep stuck in a trench, was saved, and then jumped back in the trench again. Let me see if I can find another copy

**Comment by styfle** [comment]
Fixed in #538, thanks!
